### ISSUE TITLE
Add Footnote

### ISSUE THREAD

**Issue by Edouard-Legoupil** [galalH/nansen#3]
Would be great if the package could also include the footnotes

For instance 
https://www.unhcr.org/refugee-statistics/download/?url=Xl2TOk

![image](https://github.com/galalH/nansen/assets/1789444/b2cf79e9-4bdf-4377-be9a-a5f6c1a57fc3)

**Comment by galalH** [comment]
Closing here. Please reopen at the package's new home: https://github.com/PopulationStatistics/nansen
